### ISSUE TITLE
out of memory 

### ISSUE THREAD

**Issue by haibarasfs** [hackiey/QAnet-pytorch#1]
when I run you code on 1080Ti 12G, about 20 steps,I meet out of memory
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/generic/THCStorage.cu:58
do you meet this problem?

**Comment by hackiey** [comment]
@haibarasfs I ran the code with a P100 GPU, which has 16G memory,  and you can simply reduce the batch size to 16.
