### ISSUE TITLE
A possible bug in self_attention.py

### ISSUE THREAD

**Issue by jayleicn** [hackiey/QAnet-pytorch#2]
Hi @hackiey,

Thanks for the code, I've successfully reproduced an em 67.515 results (w/o EMA)! But when I read the codes carefully, I noticed something might be wrong in self_attention.py,
```
heads = torch.zeros(self.n_heads, batch_size, l, self.value_dim, device=device)  # L30, creation
x = heads.view(batch_size, l, -1)  # L47,  resize
```
https://github.com/hackiey/QAnet-pytorch/blob/master/qanet/self_attention.py#L47

which I think should be 
```
x = heads.permute(1, 2, 0, 3).contiguous().view(batch_size, l, -1)
```

Does this make sense to you? I've also tested the code with the proposed change, but the result seems not changing. Any idea how it happens?

**Comment by hackiey** [comment]
@jayleicn Thanks for your proposed code, actually you are right, we should permute the heads first, and the reason of not changed result is the heads number is 1, I will update the codes and test it for 8 heads.

**Comment by jayleicn** [comment]
@hackiey Thanks, no wonder it is not changing at all.

**Comment by hackiey** [comment]
I have just updated the code, but I don't have enough GPU memory to test the 8 heads, we need a memory efficient method for self attention in the future.
