### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by elyase** [hackiey/QAnet-pytorch#4]
Hi, thanks for the implementation. Would you mind adding a license? Would love to try the model but right now it is not possible.

**Comment by hackiey** [comment]
@elyase Hi, there is no need for a license, you can use this model as you want.

**Comment by elyase** [comment]
Thanks but unfortunately in many countries it doesn't work like that:

https://blog.codinghorror.com/pick-a-license-any-license/
https://softwareengineering.stackexchange.com/questions/148146/open-source-code-with-no-license-can-i-fork-it

If you change your mind this is the easiest way to go about it:
https://help.github.com/articles/adding-a-license-to-a-repository/

**Comment by hackiey** [comment]
I have added a MIT license, now you can enjoy it :D
