### ISSUE TITLE
how to use multiple GPUs

### ISSUE THREAD

**Issue by leonwyang** [hackiey/QAnet-pytorch#5]
the constants.py file specifies cuda:0 as device when cuda is available, is there a way to use multiple GPUs by modifying the constants.py or other parts of the code?

**Comment by hackiey** [comment]
pytorch multiple gpus need nn.DataParallel(model).

here is the tutorial. https://pytorch.org/tutorials/beginner/former_torchies/parallelism_tutorial.html
